/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;
import com.jtattoo.plaf.smart.*;
import java.util.Properties;
import javax.swing.UIManager;
import javax.swing.JFrame;
import static view.configtestes.app;

/**
 *
 * @author renatarodriguespintos
 */
public class configtestes extends javax.swing.JFrame {
public static configtestes app = null;
    /**
     * Creates new form configtestes
     */
    public configtestes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgaluno = new javax.swing.ButtonGroup();
        configgeral = new javax.swing.JButton();
        editartestes = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("configuração de testes");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        configgeral.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        configgeral.setText("confuguracao geral da avaliacao ");
        configgeral.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        configgeral.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                configgeralActionPerformed(evt);
            }
        });

        editartestes.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        editartestes.setText("editar testes ");
        editartestes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editartestesActionPerformed(evt);
            }
        });

        jButton1.setText("exportar teste");

        jButton2.setText("importar teste");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(173, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(editartestes, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(configgeral, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(164, 164, 164))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(135, 135, 135)
                .addComponent(configgeral, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(editartestes, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2)
                .addContainerGap(119, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
        
    private void configgeralActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_configgeralActionPerformed
        // TODO add your handling code here:
     configuracaogeral config = new configuracaogeral();
        config.setLocationRelativeTo(null);
        config.setVisible(true);
        
        
    }//GEN-LAST:event_configgeralActionPerformed

    private void editartestesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editartestesActionPerformed
        // TODO add your handling code here:
        editartestes teste = new editartestes();
        teste.setLocationRelativeTo(null);
        teste.setVisible(true);
       
        
    }//GEN-LAST:event_editartestesActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgaluno;
    private javax.swing.JButton configgeral;
    private javax.swing.JButton editartestes;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    // End of variables declaration//GEN-END:variables
}
